apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-monitoring
  labels:
    app: flask-monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-monitoring
  template:
    metadata:
      labels:
        app: flask-monitoring
    spec:
      containers:
      - name: flask-monitoring
        image: hbayraktar/flask-monitoring:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: flask-monitoring-service
spec:
  type: LoadBalancer
  selector:
    app: flask-monitoring
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
